/* At BP2013B1 we belive in and live by the principle of "Security By Obscurity".
 * Hence we cannot make the source code a compiler would normally find here publicly available,
 * since distributing the code of our HPI (Highscore Protocol Implementation) would
 * violate our code of honor. Staying true to our principles we hope to ensure a fair and cheat free
 * gameing experiences.
 * However, our HPI is man made and therefore has a couple of flaws. If you feel smart enough,
 * we encourage you to try to break our algorithm and submit a score of precisely 84201381. The
 * first wise programmer to do so might receive a price.
 *
 * BP2013B1
 */
